title: Миленочка Чернуцкая — это бренд
logo: /assets/img/logo.png
description: —
show_downloads: true
theme: jekyll-theme-minimal
github:
  zip_url: http://czernucka.github.io/download.zip
  another_url: portfolio